### ISSUE TITLE
function as integrand

### ISSUE THREAD

**Issue by bill10** [TheDemx27/calculus#1]
First, thank you! It is so hard to find a package that does some simplest scientific computing in GO. Could I supply a user-defined function to the integration function instead of a string, because I am not sure how to type the sqrt function in the string?

**Comment by rpopplewell** [comment]
Well, I'm glad you found this package helpful! Feel free to "star" it. In order to use sqrt with the string input, you would just write `clc.NewFunc("sqrt(x)")`. It should work just fine. 

If you really want to use user defined functions, I just added them ( feb3d9dc1f9ed044a3846bef7fe6bc478e8fefdb ), and updated the README.md which should explain how to use them.

**Comment by bill10** [comment]
Great! I will try them tonight. Thank you!
